const html = `<div class="showcase-strip">
  <div style="display:flex;overflow:hidden;padding:2.5rem 0;">
    <div class="marquee-track" id="marquee">
      <div class="showcase-card tall"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#ddd;"></div><div class="sc-dot" style="background:#e5e5e5;"></div></div><div class="sc-body"><div class="sc-row" style="width:80%;"></div><div class="sc-row" style="width:55%;"></div><div class="sc-grid"><div class="sc-block sc-accent"></div><div class="sc-block"></div><div class="sc-block"></div><div class="sc-block sc-accent"></div></div></div></div><div class="sc-hover-label"><p class="sc-hover-phase">Phase 01</p><p class="sc-hover-title">Discovery &amp; Research</p></div></div>
      <div class="showcase-card sq"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#e0e0e0;"></div><div class="sc-dot" style="background:#ddd;"></div></div><div class="sc-body"><div class="sc-row" style="width:60%;"></div><div style="height:40px;background:var(--bg4);border-radius:4px;margin-top:4px;"></div><div class="sc-row" style="width:80%;margin-top:6px;"></div></div></div><div class="sc-hover-label"><p class="sc-hover-phase">Phase 02</p><p class="sc-hover-title">Information Architecture</p></div></div>
      <div class="showcase-card"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#ddd;"></div><div class="sc-dot" style="background:#e0e0e0;"></div></div><div class="sc-body"><div class="sc-grid"><div class="sc-block"></div><div class="sc-block sc-accent"></div><div class="sc-block sc-accent"></div><div class="sc-block"></div></div><div class="sc-row" style="width:70%;margin-top:6px;"></div></div></div><div class="sc-hover-label"><p class="sc-hover-phase">Phase 03</p><p class="sc-hover-title">Wireframing</p></div></div>
      <div class="showcase-card wide tall"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#e5e5e5;"></div><div class="sc-dot" style="background:#ddd;"></div></div><div class="sc-body"><div class="sc-row" style="width:90%;"></div><div class="sc-row" style="width:65%;"></div><div style="height:64px;background:var(--bg3);border-radius:6px;margin-top:6px;border:1px solid var(--border);"></div></div></div><div class="sc-hover-label"><p class="sc-hover-phase">Phase 04</p><p class="sc-hover-title">High-Fidelity Design</p></div></div>
      <div class="showcase-card sq"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#ddd;"></div><div class="sc-dot" style="background:#e8e8e8;"></div></div><div class="sc-body"><div class="sc-row" style="width:50%;"></div><div class="sc-grid"><div class="sc-block"></div><div class="sc-block"></div><div class="sc-block sc-accent"></div><div class="sc-block"></div></div></div></div><div class="sc-hover-label"><p class="sc-hover-phase">Phase 05</p><p class="sc-hover-title">Prototyping</p></div></div>
      <div class="showcase-card tall"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#e0e0e0;"></div><div class="sc-dot" style="background:#ddd;"></div></div><div class="sc-body"><div style="height:70px;background:var(--bg3);border-radius:6px;border:1px solid var(--border);display:flex;align-items:center;justify-content:center;"><div style="width:60%;height:8px;background:var(--ink4);border-radius:99px;opacity:0.2;"></div></div><div class="sc-row" style="width:70%;margin-top:6px;"></div></div></div><div class="sc-hover-label"><p class="sc-hover-phase">Phase 06</p><p class="sc-hover-title">User Testing</p></div></div>
      <!-- duplicates for loop -->
      <div class="showcase-card tall"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#ddd;"></div><div class="sc-dot" style="background:#e5e5e5;"></div></div><div class="sc-body"><div class="sc-row" style="width:80%;"></div><div class="sc-row" style="width:55%;"></div><div class="sc-grid"><div class="sc-block sc-accent"></div><div class="sc-block"></div><div class="sc-block"></div><div class="sc-block sc-accent"></div></div></div></div><div class="sc-hover-label"><p class="sc-hover-phase">Phase 01</p><p class="sc-hover-title">Discovery &amp; Research</p></div></div>
      <div class="showcase-card sq"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#e0e0e0;"></div></div><div class="sc-body"><div class="sc-row" style="width:60%;"></div><div style="height:40px;background:var(--bg4);border-radius:4px;margin-top:4px;"></div></div></div><div class="sc-hover-label"><p class="sc-hover-phase">Phase 02</p><p class="sc-hover-title">Information Architecture</p></div></div>
      <div class="showcase-card wide tall"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#e5e5e5;"></div></div><div class="sc-body"><div class="sc-row" style="width:90%;"></div><div style="height:64px;background:var(--bg3);border-radius:6px;margin-top:6px;border:1px solid var(--border);"></div></div></div><div class="sc-hover-label"><p class="sc-hover-phase">Phase 04</p><p class="sc-hover-title">High-Fidelity Design</p></div></div>
      <div class="showcase-card"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#ddd;"></div></div><div class="sc-body"><div class="sc-grid"><div class="sc-block"></div><div class="sc-block sc-accent"></div><div class="sc-block sc-accent"></div><div class="sc-block"></div></div></div></div><div class="sc-hover-label"><p class="sc-hover-phase">Phase 03</p><p class="sc-hover-title">Wireframing</p></div></div>
      <div class="showcase-card tall"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#e0e0e0;"></div></div><div class="sc-body"><div style="height:70px;background:var(--bg3);border-radius:6px;border:1px solid var(--border);display:flex;align-items:center;justify-content:center;"><div style="width:60%;height:8px;background:var(--ink4);border-radius:99px;opacity:0.2;"></div></div></div></div><div class="sc-hover-label"><p class="sc-hover-phase">Phase 06</p><p class="sc-hover-title">User Testing</p></div></div>
    </div>
  </div>
</div>`;

export function ShowcaseSection() {
  return <div dangerouslySetInnerHTML={{ __html: html }} />;
}
