const html = `<div class="showcase-strip">
  <p class="showcase-label">UI designs — hover to pause</p>
  <div style="display:flex;overflow:hidden;">
    <div class="marquee-track" id="marquee">
      <!-- Cards duplicated for seamless loop -->
      <div class="showcase-card"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#F7C5D0;"></div><div class="sc-dot" style="background:#EDE5DE;"></div></div><div class="sc-body"><div class="sc-row" style="width:80%;"></div><div class="sc-row" style="width:55%;"></div><div class="sc-grid"><div class="sc-block sc-accent"></div><div class="sc-block"></div><div class="sc-block"></div><div class="sc-block sc-accent"></div></div></div></div></div>
      <div class="showcase-card"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#D4EFD4;"></div><div class="sc-dot" style="background:#EDE5DE;"></div></div><div class="sc-body"><div class="sc-row" style="width:60%;"></div><div style="height:40px;background:var(--bg4);border-radius:4px;margin-top:4px;"></div><div class="sc-row" style="width:80%;margin-top:6px;"></div><div class="sc-row" style="width:40%;"></div></div></div></div>
      <div class="showcase-card"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#F7C5D0;"></div><div class="sc-dot" style="background:#EDE5DE;"></div></div><div class="sc-body"><div class="sc-grid"><div class="sc-block"></div><div class="sc-block sc-accent"></div><div class="sc-block sc-accent"></div><div class="sc-block"></div></div><div class="sc-row" style="width:70%;margin-top:6px;"></div></div></div></div>
      <div class="showcase-card"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#C5D4F7;"></div><div class="sc-dot" style="background:#EDE5DE;"></div></div><div class="sc-body"><div class="sc-row" style="width:90%;"></div><div class="sc-row" style="width:65%;"></div><div style="height:48px;background:rgba(232,84,122,0.1);border-radius:6px;margin-top:6px;border:1px solid rgba(232,84,122,0.2);"></div></div></div></div>
      <div class="showcase-card"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#F7ECD4;"></div><div class="sc-dot" style="background:#EDE5DE;"></div></div><div class="sc-body"><div class="sc-row" style="width:50%;"></div><div class="sc-grid"><div class="sc-block"></div><div class="sc-block"></div><div class="sc-block sc-accent"></div><div class="sc-block"></div></div></div></div></div>
      <div class="showcase-card"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#F7C5D0;"></div><div class="sc-dot" style="background:#EDE5DE;"></div></div><div class="sc-body"><div style="height:55px;background:rgba(232,84,122,0.08);border-radius:6px;border:1px solid rgba(232,84,122,0.15);display:flex;align-items:center;justify-content:center;"><div style="width:60%;height:8px;background:var(--pink);border-radius:99px;opacity:0.4;"></div></div><div class="sc-row" style="width:70%;margin-top:6px;"></div></div></div></div>
      <!-- Duplicate for seamless scroll -->
      <div class="showcase-card"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#F7C5D0;"></div><div class="sc-dot" style="background:#EDE5DE;"></div></div><div class="sc-body"><div class="sc-row" style="width:80%;"></div><div class="sc-row" style="width:55%;"></div><div class="sc-grid"><div class="sc-block sc-accent"></div><div class="sc-block"></div><div class="sc-block"></div><div class="sc-block sc-accent"></div></div></div></div></div>
      <div class="showcase-card"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#D4EFD4;"></div><div class="sc-dot" style="background:#EDE5DE;"></div></div><div class="sc-body"><div class="sc-row" style="width:60%;"></div><div style="height:40px;background:var(--bg4);border-radius:4px;margin-top:4px;"></div><div class="sc-row" style="width:80%;margin-top:6px;"></div></div></div></div>
      <div class="showcase-card"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#F7C5D0;"></div><div class="sc-dot" style="background:#EDE5DE;"></div></div><div class="sc-body"><div class="sc-grid"><div class="sc-block"></div><div class="sc-block sc-accent"></div><div class="sc-block sc-accent"></div><div class="sc-block"></div></div></div></div></div>
      <div class="showcase-card"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#C5D4F7;"></div><div class="sc-dot" style="background:#EDE5DE;"></div></div><div class="sc-body"><div class="sc-row" style="width:90%;"></div><div style="height:48px;background:rgba(232,84,122,0.1);border-radius:6px;margin-top:6px;border:1px solid rgba(232,84,122,0.2);"></div></div></div></div>
      <div class="showcase-card"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#F7ECD4;"></div><div class="sc-dot" style="background:#EDE5DE;"></div></div><div class="sc-body"><div class="sc-row" style="width:50%;"></div><div class="sc-grid"><div class="sc-block"></div><div class="sc-block"></div><div class="sc-block sc-accent"></div><div class="sc-block"></div></div></div></div></div>
      <div class="showcase-card"><div class="showcase-card-inner"><div class="sc-bar"><div class="sc-dot" style="background:#F7C5D0;"></div><div class="sc-dot" style="background:#EDE5DE;"></div></div><div class="sc-body"><div style="height:55px;background:rgba(232,84,122,0.08);border-radius:6px;border:1px solid rgba(232,84,122,0.15);display:flex;align-items:center;justify-content:center;"><div style="width:60%;height:8px;background:var(--pink);border-radius:99px;opacity:0.4;"></div></div></div></div></div>
    </div>
  </div>
</div>`;

export function ShowcaseSection() {
  return <div dangerouslySetInnerHTML={{ __html: html }} />;
}
